hip: add -Wno-nrvo option
When I tried to use MIGraphX against a very recent ROCm build, I got
errors of the form:

    input/main.cpp:40:8: error: not eliding copy on return [-Werror,-Wnrvo]
       40 | return zzreturn;
          |        ^

This is a warning that was added to upstream Clang in May, so as long as
-Weverything is used together with -Werror, it has to be disabled again
explicitly.